server:
  port: 8081

# 配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    hikari:
      username: root
      password: root
      # 数据库驱动
      # mysql-connector-java >= 6.x com.mysql.cj.jdbc.Driver
      # mysql-connector-java <= 5.x com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # 地址
    host: localhost
    # 端口
    port: 6379
    # 连接超时时长
    timeout: 10s
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# 引入JWT
jwt:
  secret: aaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccddddd
  # 有效期，单位秒，默认2周 1209600
  expire-time-in-second: 900

# 项目相关配置
king:
  # 名称
  name: king
  # 版本
  version: 1.1.0
  # 版权年份
  copyrightYear: 2019
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/king/uploadPath，Linux配置 /home/king/uploadPath）
  profile: E:/king/uploadPath
  # 获取ip地址开关
  addressEnabled: true